tap "jesseduffield/lazydocker"

brew "autojump"
brew "git"
brew "git-lfs"
brew "homeassistant-cli"
brew "jesseduffield/lazydocker/lazydocker"
brew "jq"
brew "lazygit"
brew "neofetch"
brew "neovim"
brew "node"
brew "ripgrep"

cask "font-hack-nerd-font"
cask "ghostty"
cask "hammerspoon"
cask "inkscape"
cask "obsidian"
cask "signal"
cask "zed"