tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "jesseduffield/lazydocker"

brew "autojump"
brew "git"
brew "git-lfs"
brew "homeassistant-cli"
brew "jesseduffield/lazydocker/lazydocker"
brew "jq"
brew "lazygit"
brew "lazygit"
brew "neofetch"
brew "neovim"
brew "node"
brew "ripgrep"
brew "zsh"

cask "devtoys"
cask "font-hack-nerd-font"
cask "hammerspoon"
cask "inkscape"
cask "obsidian"
cask "signal"
cask "zed"